# Generated by Django 6.1.1 on 2026-09-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.PositiveIntegerField(help_text="Duration (Mins)"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
