# Generated by Django 6.1.1 on 2026-10-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_unique_seat_per_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_booked',
        ),
    ]
