# Generated by Django 6.1.1 on 2026-10-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_seat_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, help_text='Poster image URL'),
        ),
    ]
